export enum Verdict {
    RUNNING = "RUNNING",
    ACCEPTED = "ACCEPTED",
    TIME_LIMIT_EXCEEDED = "TIME_LIMIT_EXCEEDED",
    MEMORY_LIMIT_EXCEEDED = "MEMORY_LIMIT_EXCEEDED",
    WRONG_ANSWER = "WRONG_ANSWER",
    RUN_TIME_ERROR = "RUN_TIME_ERROR",
    COMPILE_TIME_ERROR = "COMPILE_TIME_ERROR",
}